### ISSUE TITLE
Lagrange crashes when it gets redirect response immediately after entering input

### ISSUE THREAD

**Issue by aegis-dev** [skyjake/lagrange#148] opened 2021-02-08 20:14 UTC
Hey! Lagrange keeps crashing from time to time after I do one very specific scenario. It happens not immediately but like after 5th or so attempt (I know, very specific... sorry). I discovered this issue while testing my framework and I wouldn't be suprised if I am doing something wrong but I think crash is not expected anyway. I will paste server code snippet that maybe will help to understand scenario.

```
  app.OnRequest("/input", (request, response) => {
      if (request.Parameters == null)
      {
          response.SetInputHint("Please enter something: ");
          response.Status = StatusCode.Input;
      }
      else
      {
          // redirect with parameters to /show route
          response.SetRedirectURL(request.BaseURL + "/show?" + request.Parameters);
          response.Status = StatusCode.RedirectTemp;
      }
  });

  app.OnRequest("/show", (request, response) => {
      if (request.Parameters == null)
      {
          // redirect back to /input
          response.SetRedirectURL(request.BaseURL + "/input");
          response.Status = StatusCode.RedirectTemp;
      }
      else
      {
          // show what you entered
          response.RenderPlainTextLine("# " + request.Parameters);
      }
  });
```
  
  Steps to reproduce:
  1. access route which responds with status code "10", in this case "/input"
  2. enter anything
  3. server gets request with "/input?something" and immediately redirects to "/show?something" (I've tried relative and absolute URL - reproducible with both)
  4. repeat until Lagrange crashes - usually 4-8 attempts.
  
  I've tried other browsers and I couldn't reproduce the issue.
  
  Please let me know if you need any additional info.
  
  P.S. I love your browser!

**Comment by skyjake** [comment] 2021-02-10 06:08
I'll try to figure out a way to reproduce this. I have seen a couple of crashes recently related to requests that finish very quickly, so there could be a race condition somewhere.

**Comment by skyjake** [comment] 2021-02-10 10:53
I did fix one launch-crasher for v1.1.2, please test and let me know if this issue is still happening with it.

**Comment by aegis-dev** [comment] 2021-02-10 16:30
I was still able to reproduce the issue. However, this time it took way longer to reproduce. I sense some UB here. Also, from time to time Lagrange terminates session connection early when server attempts to read request but that might be unrelated. Are there any logs or info I could provide you? I guess I could provide you a repro server binary for your platform. Unfortunately, I am not able to host repro somewhere at the moment.

**Comment by skyjake** [comment] 2021-02-10 16:54
A Linux x86_64 repro server binary would be most helpful.

**Comment by aegis-dev** [comment] 2021-02-10 17:04
This is .net 5.0 self container binary. Shouldn't require any dependencies and should fly out of the box. Too large so uploaded to gdrive. 
https://drive.google.com/file/d/1-nPQMBycZcvoHj9nLFyO5MvIbcJSLEdd/view?usp=sharing

To run server you will need a certificate:
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privatekey.key -out certificate.crt`
This example will require directory to serve argument, so just pass any empty dir, content is rendered dynamically.

to reproduce launch server and go to gemini:.//127.0.0.1/
input something and then click the link in response. Repeat until crash occurs. For me it reproduces instantly now.

Hope it helps!

**Comment by skyjake** [comment] 2021-02-14 11:51
@aegis-dev  Just an update: I haven't been able to access your Google Drive link...

**Comment by aegis-dev** [comment] 2021-02-14 12:37
@skyjake my apologies! 🙏  You should be able to access it now.

**Comment by skyjake** [comment] 2021-02-18 07:19
Thanks! I tried to reproduce this and even after multiple attempts I couldn't get it to crash.

Would it be possible for you to make a debug build of Lagrange and get a backtrace of the crash?

**Comment by aegis-dev** [comment] 2021-02-18 08:05
Alright, I will take a look

**Comment by skyjake** [comment] 2021-03-03 08:02
One possible explanation is #181. Requests that completed very quickly may have sent an update notification after they had already finished, causing a potential crash.

**Comment by aegis-dev** [comment] 2021-03-03 09:44
I didn't have much time lately to check this issue myself, sorry. Let me know whenever you release with this fix and I will definitely check if issue is still reproducible.

**Comment by skyjake** [comment] 2021-03-03 09:46
The fix for #181 is included in [v1.2](https://github.com/skyjake/lagrange/releases/tag/v1.2.1).

**Comment by aegis-dev** [comment] 2021-03-05 20:04
Unfortunately still crash 😞

**Comment by skyjake** [comment] 2021-03-07 12:31
I've pushed some multithreading fixes to the dev branch, they could be of help here.

**Comment by skyjake** [comment] 2021-04-23 20:33
I'm fairly certain 480f3b7e9526d2219267d5426a7c997574846d59 resolves this issue.

**Comment by aegis-dev** [comment] 2021-04-24 09:44
Crashed with v1.3.3, unfortunately. I can provide you a windows server binary which reproduces the crash. This time repro is even simpler. I just create an infinite redirect loop. Even if your browser prompts that you are in the loop, click on the link to continue looping and eventually browser will crash. 

Also, I wanted to mention that browser crashes usually after it sends 0 byte request to the server.

https://drive.google.com/file/d/1l0El-J1sJoilYeixZakd7r7E7H7CtfDq/view?usp=sharing

`CuipodExample.exe <path to empty dir>/ <path to cert>/certificate.crt <path to private key>/privatekey.key`

**Comment by aegis-dev** [comment] 2021-04-24 09:47
Serving capsule on 0.0.0.0:1965
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
Exception:  Received an unexpected EOF or 0 bytes from the transport stream.
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
gemini://127.0.0.1/
gemini://127.0.0.1/show
Exception:  Received an unexpected EOF or 0 bytes from the transport stream.
Exception:  Received an unexpected EOF or 0 bytes from the transport stream.


It takes a bit of time to reproduce but as I mentioned before browser eventually crashes. As you can see, server receives some empty requests before the crash.

**Comment by skyjake** [comment] 2021-04-25 04:14
> Crashed with v1.3.3, unfortunately. I can provide you a windows server binary which reproduces the crash.

Thanks, I'll check out your `CuipodExample.exe` and verify whether 480f3b7e9526d2219267d5426a7c997574846d59 affects this.

**Comment by skyjake** [comment] 2021-04-25 06:14
I can now somewhat reliably reproduce a crash with `CuipodExample.exe`, although frustratingly it's much more difficult to do so when running in a debugger. The problem may be specific to Windows and its event loop behavior, which is why I haven't encountered it before.

**Comment by skyjake** [comment] 2021-04-25 13:42
I also found a race in the async starting of a socket connection. It was possible that address lookup finished exactly at the same time as another thread requested the socket to be opened, causing the async connection thread to be started twice. This naturally caused one of them to fail, and thus the connection was aborted.

Let's see if this is the elusive bug that's been the culprit here!

(It would also be better to not do async address lookups for numeric IP addresses...)

**Comment by skyjake** [comment] 2021-04-26 10:13
Several related fixes are included in [v1.3.4](https://github.com/skyjake/lagrange/releases/v1.3.4), please test and see if those work on your system.

I am now unable to reproduce the crash, but it appears the serverside "unexpected EOF" issue is still occurring on v1.3.4 when repeating redirects.

**Comment by aegis-dev** [comment] 2021-04-26 13:16
Thanks for letting me know. I will test that later today. Also, I will compare behavior to other gemini clients and see if I get "unexpected EOF" error with them too. I will let you know about the results 👍

**Comment by aegis-dev** [comment] 2021-04-30 10:39
I got some good news... Lagrange no longer crash and I don't see any `unexpected EOF` errors in server side 😄 Nice! I guess  you can close the ticket 🥇

**Comment by aegis-dev** [comment] 2021-04-30 10:45
I spoke too soon 😅 I got few `unexpected EOF` that occur at random but no crash... I couldn't reproduce `unexpected EOF` with other gemini browsers. I suspect some kind of concurrency problem in Lagrange threading.

**Comment by skyjake** [comment] 2021-04-30 10:50
👍 

Now the question is, does that EOF ever get triggered in "normal" use or is it happening only in this synthetic stress test?

I agree there is likely some rare condition that leads to closing the socket prematurely. Please submit a new issue for that bug if you feel it is worth the time investment, i.e., if it's breaking your server/service.

**Closed as completed by skyjake** 2021-04-30 10:50 UTC
Labels: bug

**Comment by aegis-dev** [comment] 2021-05-03 08:28
I don't have any good repro for EOF case at the moment and it doesn't break anything for me. However, keep in mind that the previous crash together with EOF was reproducible in "normal" conditions. I will create a new ticket if I encounter EOF in normal conditions. Good luck 👋
