### ISSUE TITLE
Lagrange v1.4.0 on Ubuntu 20.04 - occasionally segfaults when opening a site/capsule

### ISSUE THREAD

**Issue by GiovanniMoretti** [skyjake/lagrange#272] opened 2021-05-09 01:17 UTC
Mostly it's fine but it (V1.4) has died twice previously. This has only since upgrading to v1.4 - running the 64 bit AppImage.

From syslog:
   kernel: [243993.057154] AppRun[67996]: 
   segfault at d400000002 
   ip 000000d400000002 
   sp 00007fff35cf06f8 error 14 in lagrange[55bdfb70f000+106000]

Nothing unexpected about the intended site.

**Comment by skyjake** [comment] 2021-05-09 03:31
Sorry to hear that! I haven't tested the AppImage extensively so it is possible it has a bug that I haven't run into. Version 1.4 also had quite sweeping internal changes so new issues were undoubtedly introduced. I'll see if I can dig up anything useful with that syslog, but if you happen to do a debug build and can reproduce the crash with it, that would be extremely helpful.

**Comment by skyjake** [comment] 2021-05-22 08:54
I've tagged this as "needs testing" because I've been unable to reproduce a crash.

**Comment by skyjake** [comment] 2021-09-18 18:38
Closing because there is no actionable info nor other reports of crashes.

**Closed as completed by skyjake** 2021-09-18 18:38 UTC
Labels: bug, needs testing
