### ISSUE TITLE
si_init_perfcounters: max_sh_per_se = 2 not supported 

### ISSUE THREAD

**Issue by dquark** [skyjake/lagrange#303] opened 2021-07-08 11:55 UTC
Hi, this is the issue I get from flatpak version on Fedora 34 with wayland:

> flatpak run fi.skyjake.Lagrange
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  147 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  100
  Current serial number in output stream:  106

**Comment by skyjake** [comment] 2021-07-08 11:57
There was a similar issue reported before: #293

Unfortunately, AFAIK no clear solution was found: https://github.com/skyjake/lagrange/issues/293#issuecomment-857573548

**Comment by skyjake** [comment] 2021-07-08 12:01
As I comment in that thread, this is most likely either a bug in [SDL](https://libsdl.org) or an issue with the installed graphics drivers. Since Lagrange handles its graphics exclusively via SDL, there isn't much that can be done in the app to resolve this.

**Comment by dquark** [comment] 2021-07-08 16:22
Just wanna mention that appimage works with no problem. Are you planning to add lagrange to more repositories? It would be great to see it as .rpm package.

**Comment by nlfx** [comment] 2021-07-30 19:43
I just switched my Fedora 34 to Wayland (NVIDIA card with nouveau driver) and also encountered this bug.

Adding `--socket=wayland` and `--socket=fallback-x11` to the `finish-args` in the flatpak manifest, fixes the issue for me.

The equivalent temporary workaround is to add the following override in `~/.local/share/flatpak/overrides/fi.skyjake.Lagrange`
```
[Context]
sockets=fallback-x11;wayland
```

Thanks a lot for this great Gemini client! :smiley:

**Comment by skyjake** [comment] 2021-07-31 04:49
Thanks for the tip! I'll give those options a try.

**Comment by nlfx** [comment] 2021-07-31 07:51
I've tested the newly published Flatpak with both Wayland and X11, and using the proprietary NVIDIA driver and the open source nouveau one. Lagrange Flatpak works perfectly in all configurations on my machine.

The only small issue I had with Wayland was the content not adapting to a resized window until the mouse goes over the window, but I see that this is already very well described in [issue #264](https://github.com/skyjake/lagrange/issues/264#issuecomment-840902462), and is not a bug which really breaks any functionality.

Thanks a lot for the great work and this quick update!

**Comment by skyjake** [comment] 2021-07-31 09:58
Closing the issue as resolved.

Feel free to reopen @dquark if the problem persists with the new builds / overrides.

**Closed as completed by skyjake** 2021-07-31 09:58 UTC
Labels: question, linux, wayland
