### ISSUE TITLE
Nonexistent host or host with no Gemini server -> crickets

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#100] opened 2020-12-15 01:40 UTC
To replicate, try gemini://example.com and then gemini://ibm.com.  There is no indication that anything is wrong, not even a cleared screen.

**Comment by skyjake** [comment] 2020-12-15 05:03
I'm getting a timeout error (on macOS), which is this the intended behavior. This doesn't happen on your platform?
<img width="743" src="https://user-images.githubusercontent.com/1225742/102173333-79dc3c80-3ea3-11eb-9b4d-a89e27c46836.png">

**Comment by johnwcowan** [comment] 2020-12-16 17:31
I'm using v0.8 on MacOS Catalina, and when I rechecked just now the issue is unchanged.  It doesn't matter if you start with an "about" screen, a regular page, or an error page, either.

**Comment by skyjake** [comment] 2020-12-16 18:57
The timeout error page was added in v0.12, released on December 5th.

**Comment by skyjake** [comment] 2020-12-19 05:36
Closing as this issue has been resolved in recent versions. Please reopen if there are still problems after upgrading.

**Closed as completed by skyjake** 2020-12-19 05:36 UTC
Labels: question
