### ISSUE TITLE
Dual Stack (IPv4+v6) failover not working

### ISSUE THREAD

**Issue by waweic** [skyjake/lagrange#43] opened 2020-11-19 09:39 UTC
When querying a dual stack server that has no route via v6 but via v4, Lagrange prints the following error message:

```
🖧 Network/TLS Failure
Failed to communicate with the host. Here is the error message:

>Network is unreachable
```

Due to peculiarities in my network, it seems that I can't get a route to gemini.circumlunar.space via v6, although it has a working AAAA record and my Computer has a somewhat working IPv6-connection. Disabling v6 altogether makes Lagrange use a working v4 connection.

IIRC the recommended behaviour for situations like these is some failover functionality, which Lagrange doesn't seem to have at this point. Would this be better suited for the_Foundation or for Lagrange? Would this even be a wanted feature?

**Comment by skyjake** [comment] 2020-11-19 10:06
This is functionality coming from the_Foundation.

There may be a bug in `connectAsync_Socket_()` where it tries to connect via all the known IP addresses, assuming that both v4 and v6 addresses were returned from `getaddrinfo()`. I'm sure there's also some platform-specific peculiarities; my knowledge of this stuff is pretty surface-level.

Might be useful to poke around in platform/posix/address.c and platform/posix/socket.c in the_Foundation and see if the addresses and the connection behavior looks right.

**Comment by rodolphoeck** [comment] 2020-12-01 20:37
I just ran into one of these possible bugs. On v0.11.0, running on Big Sur dual-stacked the application freezes the whole OS - the only way I found to fix the issue is to reboot.

**Comment by skyjake** [comment] 2020-12-02 08:56
@rodolphoeck I've seen a couple of weird freezes on Big Sur, although not recently. An app shouldn't be able to hang the whole system, and also this never occurred on Catalina, so I'm willing to bet there's a Big Sur bug in play here somewhere.

I'll keep me eye on it, as I do develop Lagrange primarily on Big Sur.

**Comment by rodolphoeck** [comment] 2021-01-04 14:45
Just noticed "dig" was also causing Big Sur to crash, so started investigating and found this https://www.obdev.at/support/littlesnitch/245917249297644 - the crash reports for the Lagrange hangs showed me the same errors, so this looks like an Apple bug (in my case with dual-stack).

**Comment by bdk0** [comment] 2021-01-20 17:08
I'm experiencing this issue after building lagrange on FreeBSD. I've dug into it a little, and I think I've narrowed down the cause:

- runAddress_ lookup returns both IPv4 and IPv6 addresses for a domain
- open_Socket_ creates a new socket. The Socket is an IPv6 socket because an IPv6 address is in the list
- open_Socket calls connectAsync_Socket_ in a new thread
- connectAsync_Socket_ first attempts to connect to the IPv4 address on the socket passed in. Since this socket is an IPv6 socket, the 'connect' call returns 'Invalid Argument'
- connectAsync_Socket_ next tries to connect to the IPv6 address, but gets a network error because IPv6 isn't routable on my home network

So if a host has both IPv4 and IPv6 address, and the IPv6 address is not routable, the Ipv4 address will never be used, since it can't connect on the IPv6 socket.

I'm not sure how to go about fixing this, but as a workaround, I've modified runAddressLookup_ on my system to always set .ai_family to AF_INET. This causes IPv6 addresses to not be returned, in effect disabling IPv6.

**Comment by skyjake** [comment] 2021-01-20 17:32
Thanks, that sounds very helpful! I should be able to make some changes based on this.

**Comment by skyjake** [comment] 2021-02-09 17:52
Could be fixed now in the dev branch, with the updated the_Foundation submodule.

The fix is included in v1.1.2.

**Comment by miluxmilux** [comment] 2021-02-16 09:23
I was experiencing similar problems. Now after the 1.1.2 and 1.1.3, Lagrange just crashes when calling a capsule. Not sure if this always happens. I also have an IPv4/v6 dual stack configuration (on MacOS Big Sur) it seems. This crash just made me realize that, I was not aware of it. I'm sending you the complete report per e-mail.

Edit: I seem to also have a routing problem on my router, since I get a TLS timeout. But this still should not crash the app, right?

**Comment by skyjake** [comment] 2021-02-16 10:44
Yeah it shouldn't crash... Seeing the crash log should be quite helpful. 👍

**Comment by skyjake** [comment] 2021-04-17 07:04
I finally managed to set up IPv6 for myself (via a tunnel) and found some bugs related to IPv6. One was that a [literal IPv6 address would be used for SNI](https://git.skyjake.fi/skyjake/the_Foundation/commit/124888dfaf4fbbe9b5d4b574bfa099f79ab72142). The other was that the URL parser didn't discard the brackets from a literal IPv6 address (927a64c9c50f3ce5cf8285ce3ee1dc9f2985d746).

**Comment by skyjake** [comment] 2021-04-18 05:24
I believe the original reported issue has been resolved (attempting connections both via IPv4 and IPv6) and after testing IPv6 on Mac and Linux I'm confident enough to declare this as fixed.

**Closed as completed by skyjake** 2021-04-18 05:24 UTC
Labels: bug, the_Foundation, needs testing
