### ISSUE TITLE
Set clipboard contents when selecting text — Xorg implicit/passive clipboard interaction

### ISSUE THREAD

**Issue by benthor** [skyjake/lagrange#262] opened 2021-05-03 14:47 UTC
I'm a long time Xorg user and I prefer to interact with my clipboard passively/implicitly by simply selecting text and middle-mouse-buttoning it somewhere else. I often interact with browser URL bars like this, but Lagrange only appears to copy selected text to clipboard after you hit Ctrl+C. Pasting using the MMB appears to work decently enough though.

**Comment by skyjake** [comment] 2021-05-03 14:54
This sounds like the same issue as #162. Do you agree?

**Comment by benthor** [comment] 2021-05-03 15:52
#162 is indeed related. From an admittedly selfish perspective, I feel that my particular issue might be resolved by simply calling `SDL_SetClipboardText()` once a selection is made, without waiting for a keyboard trigger. This would cause the selection to end up in the primary clipboard and represent standard Xorg convention. Dealing with Ctrl+C in the way that people seem to expect appears to be more work.

**Comment by benthor** [comment] 2021-05-03 15:53
[Related discussion about X clipboards](https://superuser.com/questions/200444/why-do-we-have-3-types-of-x-selections-in-linux)

**Comment by skyjake** [comment] 2021-05-04 07:39
>  issue might be resolved by simply calling SDL_SetClipboardText() once a selection is made

That could work some of the time / for some people, but I think that it's better to follow the convention fully, as suggested in #162.

Closing as duplicate of #162.

**Closed as completed by skyjake** 2021-05-04 07:39 UTC
Labels: duplicate, enhancement
