### ISSUE TITLE
Black areas in Sidebar and page area after some time

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#57] opened 2020-11-23 20:36 UTC
- v0.9.0 6e1e7d061996c01ea7c3386620b1b52800401715, compiled on Debian bullseye.

I noticed this multiple times after I kept Lagrange open, but was not using it for a longer time.

I tried to reproduce it with turning screensaver on, suspending my laptop, switching desktops, but was unable to reproduce due to these reasons.

The blackness disappears after you hover over the bookmarks, but not from the page area (see screenshot).
![lagrange-black-after-some-time](https://user-images.githubusercontent.com/41564/100012685-53fbd480-2ddc-11eb-8dcf-9b05d1f15a40.png)

**Comment by skyjake** [comment] 2020-11-24 06:14
I've seen this myself (pretty rarely, though), but haven't yet pinpointed the reason. Generally speaking, it's because the buffered visuals are lost, but SDL should notify when redrawing them is needed.

Which version of SDL is available on your system?

**Comment by emilis** [comment] 2020-11-24 06:59
```
Package: libsdl2-dev
Version: 2.0.12+dfsg1-4
```

**Comment by emilis** [comment] 2020-12-02 21:18
Just noting, that it is still present in 0.11.

**Comment by skyjake** [comment] 2021-02-10 06:25
I recently managed to reproduce a bug like this when testing fullscreen mode for v1.2, and applied a fix. Perhaps it will help with this issue, too.

**Comment by skyjake** [comment] 2021-03-17 07:05
Given that this is an old report and no one has reported similar issues, I'm assuming this has been fixed by the recent (v1.2) window redrawing changes.

**Closed as completed by skyjake** 2021-03-17 07:05 UTC
Labels: bug
