### ISSUE TITLE
macOS: Two-finger-single-tap menu doesn't match control-click menu

### ISSUE THREAD

**Issue by adiabatic** [skyjake/lagrange#621] opened 2023-09-12 06:46 UTC
For a while I wondered why Lagrange doesn't have conveniences like "Open in New Window" when I right-click on links. Lagrange is fantastic in lots of ways, so this seemed like a very odd omission.

Turns out, it does have them.

It's just that when I do a two-finger single tap (the normal gesture for pulling up a context menu), I get the normal context menu (`Go Back` … `Save to Downloads`).

However, if I hold down the Control key and tap on a link (the way to generate a right-click if you have a puny one-button mouse), I get a proper link context menu with options like `Open Link in New Tab` and whatnot.

Could the control-click menu become the menu for the two-finger single tap?

Thanks!

**Comment by skyjake** [comment] 2023-09-12 14:05
I can confirm this is not working as intended. I have been noticing some tap-to-click weirdness in macOS recently, so this may be a lower-level problem.

I'll have to take a closer look at the events. With the two-finger single tap there seems to be some sort of a system-induced delay between the tap and the action, causing Lagrange to lose its hover state on the link, and thus the normal page context menu is shown.

**Comment by skyjake** [comment] 2023-09-12 14:27
Turned out it was a simple fix. Will be included in the next release.

**Closed as completed** 2023-10-08 08:59 UTC
Labels: bug, macos
