### ISSUE TITLE
Caps Lock as Ctrl is broken

### ISSUE THREAD

**Issue by lifelike** [skyjake/lagrange#219] opened 2021-03-26 06:27 UTC
Keyboard shortcuts using control do not work for me in Linux with Caps Lock remapped to Ctrl. I have to reach for the physical Ctrl button on the keyboard instead of using the Caps Lock key that works in all other applications to press ctrl-R or any other shortcut.

**Comment by skyjake** [comment] 2021-03-26 06:50
I believe this happens because SDL, the library Lagrange uses for input and window management, talks to the keyboard at a lower level than X keyboard mappings.

There is a workaround in the upcoming v1.3 (current dev branch) that could help, though (see issue #87). There will be a new configuration file called `modmap.txt` where you can reassign Lagrange's modifier keys as appropriate, so you can replicate the Caps Lock → Control mapping there.

**Comment by skyjake** [comment] 2021-03-26 06:59
Closing as duplicate of #87.

**Closed as completed by skyjake** 2021-03-26 06:59 UTC
Labels: duplicate, linux
