### ISSUE TITLE
Style option for alignment of first preformatted block

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#55] opened 2020-11-23 20:27 UTC
Steps to reproduce:

- Go to SpaceWalk <gemini://rawtext.club:1965/~sloum/spacewalk.gmi>.

Result:

- The horizontal lines in the preformatted logo block, do not align vertically with the line below the text "Updates" (see screenshot).

![lagrange-heading-alignment](https://user-images.githubusercontent.com/41564/100011428-6248f100-2dda-11eb-8a0b-1c6640ea39f3.png)

Expected result:

- ASCII art aligns throughout the page.

Discussion:

- I would like for the h1, h2, h3 headings to align with the text too, but it's just my preference.
- It seems that the site icon at the top does not align vertically with headings or link icons.

**Comment by skyjake** [comment] 2020-11-24 06:19
This is working as intended. I will consider adding a style preference for the alignment(s).

**Comment by skyjake** [comment] 2021-09-18 19:16
I'm going to close this issue because I've decided not to add an option specifically for this. However, in the future, it would be nice to have a selection of themes for different page appearances. Depending on how these themes are configured (perhaps in a text file), among the parameters can be indentation widths for each line type.

**Closed as completed by skyjake** 2021-09-18 19:16 UTC
Labels: enhancement, suggestion
