### ISSUE TITLE
Rasperry Pi touchscreen issue: flinging sensitivity

### ISSUE THREAD

**Issue by tobykurien** [skyjake/lagrange#166] opened 2021-02-17 05:59 UTC
Probably something to do with SDL, but I cannot use the interface with touch, the taps don't register at all. Long-press for context menu doesn't work either. These work in other apps. I am using a Waveshare HDMI screen with USB touch interface.

Plugging in a mouse works, but it would be nice if I could browse gemini in tablet mode.

**Comment by skyjake** [comment] 2021-02-17 19:08
I'm planning to handle SDL's touch events in addition to mouse events. Assuming the touchscreen is generating events via SDL, this should allow it to work with Lagrange.

**Comment by skyjake** [comment] 2021-03-01 04:30
@tobykurien v1.2 handles SDL touch events if they are being sent to the app. These may or may not help with your Raspi touch screen.

**Comment by tobykurien** [comment] 2021-03-01 05:37
Thanks @skyjake I have tested now with v1.2.1, and touch does now work! There is an issue with scrolling using tap and drag - if you tap and drag even very slightly, the document shoots to the to or the bottom at full speed. I am able to work around this by dragging the scrollbar on the right instead. Seems to be a sensitivity issue for flinging. Is there somewhere in the code I can change this sensitivity? Anyway, super excited that I can use Lagrange on my Rpi tablet now, so thank you for the great work!

**Comment by skyjake** [comment] 2021-03-01 05:57
The code for that is here: https://github.com/skyjake/lagrange/blob/08279486f60cbd81bda35e0fb8ed418b821ec8a6/src/ui/touch.c#L394

The Momentum instances are responsible for scrolling after a swipe completes. Something must be wrong with the `velocity` math... You could try scaling it down by some factor? The way it's calculated at the moment is intended to be generally applicable to all devices, though.

A possible explanation is that [this](https://github.com/skyjake/lagrange/blob/08279486f60cbd81bda35e0fb8ed418b821ec8a6/src/ui/touch.c#L375) doesn't have valid values for calculating the speed of the completed swipe.

**Comment by tobykurien** [comment] 2021-03-01 06:06
It appears to be affected by the UI scale factor, my screen is high dpi so I had scaling at 2. At 1, the momentum is lower, but still too high.

**Comment by skyjake** [comment] 2021-03-01 06:13
Hmm, I may know what the problem is: DocumentWidget does per-pixel scroll events only on Apple platforms at the moment. I need to change this so that the generated events are flagged if they per-pixel scrolls, and touch.c can then send those.

You could try changing [this line](https://github.com/skyjake/lagrange/blob/08279486f60cbd81bda35e0fb8ed418b821ec8a6/src/ui/documentwidget.c#L2318) so it is enabled always:

```
#if 1
```

If that helps, there is a similar scroll processing case in ListWidget.

**Comment by tobykurien** [comment] 2021-03-01 06:37
Yes, that fixed it :+1:

**Comment by skyjake** [comment] 2021-03-01 07:16
I'll do some improvements in the event processing. It anyway needs some cleanup due to the platform-specific differences.

**Comment by ghost** [comment] 2021-03-01 17:20
Tried it on my Mobian Pinetab. Worked fine apart from the very fast scrolling (maybe about 50:1 “gearing” I'd guess) with simple dragging but, as with the Pi noted above, the side scroll bar worked fine.

Changing documentwidget.c line 2318 as suggested above fixes the problem - scrolling then works nicely.

**Comment by skyjake** [comment] 2021-03-07 12:18
@tobykurien @ed-davies The dev branch now has improved touch event handling. The touchscreens in your devices should (hopefully!) now work without changes to the source.

**Comment by tobykurien** [comment] 2021-03-08 16:38
I tried the latest release v1.2.2, but no luck. I am guessing you are referring to changes in the dev branch that are not released? I'll wait for a release as I don't know what goes into making the .tar.gz file in the releases.

**Comment by skyjake** [comment] 2021-03-08 17:42
Yeah these changes are not part of any release at the moment.

**Comment by tobykurien** [comment] 2021-03-08 17:48
While I was testing the previously modified build, I noticed a few things:

- flinging stopped working randomly after some time. I had to quit and restart the app to make it work again

- cannot copy text by tapping, double tapping, or long pressing text

I am posting here as FYI, didn't want to log these as I would rather test a release.

On 8 March 2021 19:42:18 GMT+02:00, "Jaakko Keränen" <notifications@github.com> wrote:
>Yeah these changes are not part of any release at the moment.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/skyjake/lagrange/issues/166#issuecomment-792941439

-- 
tobykurien.com | @tobykurien

**Comment by skyjake** [comment] 2021-03-08 17:51
>  cannot copy text by tapping, double tapping, or long pressing text

Activation of the text selection mode is not implemented yet. It's likely going to be a long-press context menu item ("Select").

**Comment by skyjake** [comment] 2021-03-18 16:53
I'm closing this issue as the original problem has been solved.

> flinging stopped working randomly after some time

Let's keep an eye on this, it may be an issue with SDL since similar problems aren't happening on other touch devices.

**Closed as completed by skyjake** 2021-03-18 16:53 UTC
Labels: enhancement

**Comment by tobykurien** [comment] 2021-03-22 15:16
Unfortunately the fix doesn't appear to be in release 1.2.3. Hopefully you won't forget to add the fix to the next release.

**Comment by skyjake** [comment] 2021-03-22 15:23
I'm considering the touch event processing changes to be too invasive to be released as a 1.2.x patch. All touch changes are going to the 1.3 release for the time being.

**Comment by stacyharper** [comment] 2021-03-31 06:59
Thanks for this work. I was also experiencing too blazing fast scroll on Pinephone. Now it is perfect :D

**Comment by skyjake** [comment] 2021-04-01 12:26
Glad to hear it!
