### ISSUE TITLE
An errant pixel lights up on selected toolbar icons (XUbuntu 20.04)

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#336] opened 2021-09-18 15:33 UTC
I am on XUbuntu 20.04, Lagrange 1.6.5 locally compiled.

When mousing over the top toolbar over any icon (back-arrow, outline of a personl, home, etc (but not the URL bar), an errant pixel lights up, same color as the frame surrounding the icon.  The pixel is located upper-leftish.

**Comment by skyjake** [comment] 2021-09-18 17:34
Could you attach a screenshot, please?

The frames are drawn as lines, and I have noticed various minor line drawing glitches on older versions of SDL. Ubuntu 20.04 has SDL 2.0.8 IIRC.

Due to lines being unreliable, I'll likely switch to some other method of drawing them in the future.

**Comment by stacksmith** [comment] 2021-09-18 18:20
I've been trying to figure out how to take a screenshot, as the tool needs to be selected which deselects the screen grabbing app, even with a screen-grab-delay set...

**Comment by stacksmith** [comment] 2021-09-18 18:26
OK, here it is.  
![lagrange-bug](https://user-images.githubusercontent.com/732800/133899273-da4ca7c8-b37c-495e-82f9-44c9e59a4c2a.png)
Also, note the noisy background!  I was planning to report this separately, but could not catch it as it is intermittent.

**Comment by skyjake** [comment] 2021-09-18 18:32
Thanks! I do recall seeing this "corner dot" issue before, but not with recent SDL versions.

The random noise has been reported before, and appears to be some glitch in the hardware accelerated SDL textures. In #271 (also Ubuntu 20.04) it was noted that forcing software rendering in Lagrange will make the issue disappear, but no real fix was found because I've been unable to reproduce the issue on my systems.

Using software rendering may help with the errant dots, as well.

**Comment by stacksmith** [comment] 2021-09-18 18:44
I did not see an option to select software rendering in Lagrange settings - is it a compile-time option?
Here are my SDL library versions, in case it is useful:
```
$ dpkg -l | grep sdl
ii  libsdl-gfx1.2-5:amd64                    2.0.25-11                                  amd64        drawing and graphical effects extension for SDL
ii  libsdl-gfx1.2-dev:amd64                  2.0.25-11                                  amd64        development files for SDL_gfx
ii  libsdl-image1.2:amd64                    1.2.12-12                                  amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2:amd64                    1.2.12-16build1                            amd64        Mixer library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl-mixer1.2-dev:amd64                1.2.12-16build1                            amd64        Mixer library for Simple DirectMedia Layer 1.2, development files
ii  libsdl1.2-dev                            1.2.15+dfsg2-5                             amd64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:amd64                    1.2.15+dfsg2-5                             amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                      2.0.10+dfsg1-3                             amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                        2.0.10+dfsg1-3                             amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64                2.0.5+dfsg1-2                              amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                  2.0.5+dfsg1-2                              amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64                2.0.4+dfsg1-2build1                        amd64        Mixer library for Simple DirectMedia Layer 2, libraries
```
Let me know if I can help in some other way

**Comment by skyjake** [comment] 2021-09-18 18:45
Try launching the app with the `--sw` command line option, no recompilation needed.

**Comment by stacksmith** [comment] 2021-09-18 18:48
--sw seems to eliminate the dot, and probably the noise (although the noise was hard to catch...)

**Comment by skyjake** [comment] 2021-09-21 15:26
I'm closing this because I don't believe there is much to be done here. The underlying issue is most likely caused by a bug in an obsolete version of SDL.

**Closed as completed by skyjake** 2021-09-21 15:26 UTC
Labels: bug

**Comment by cloudrac3r** [comment] 2022-02-17 23:17
I had the same issue on Ubuntu 20.04 locally compiled, including the glitchy background on the URL bar. The `--sw` workaround did the trick. Thank you!

**Comment by stacksmith** [comment] 2022-02-19 18:11
I still see glitches (weird pieces of bitmaps) in the background of the URL bar...  LaGrange 1.10.2, on xubuntu 20.04.3 LTS

**Comment by skyjake** [comment] 2022-02-20 05:41
@stacksmith You mean like #271 ?

**Comment by stacksmith** [comment] 2022-02-22 14:03
I think so... I am so used to it I hardly notice it - it is only on the URL bar.

**Comment by skyjake** [comment] 2022-02-22 14:07
As far as I can tell, that glitch is either a bug in the version of SDL in Ubuntu 20.04, or some video driver issue. There are no reports of it with newer SDL releases.
