### ISSUE TITLE
Client ignores URI fragment identifiers

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#128] opened 2021-01-31 05:26 UTC
I have a line in a gmi file that goes like this:
`=> https://matrix.to/#/@user:matrix.org   Matrix Account`

Instead of linking to `https://matrix.to/#/@user:matrix.org`, it only links to `https://matrix.to/`

This doesn't seem to be an issue in other clients.

**Comment by skyjake** [comment] 2021-01-31 05:32
Ah, the problem seems to be that this behavior of stripping URL fragments is being applied to all URLs when it should only affect Gemini URLs.

**Comment by johnwcowan** [comment] 2021-02-02 04:46
The same rules apply to all URLs.  For a brief period, Google Chrome passed fragments beginning with ! to the server, but nowadays the fragment is normally sent along by Javascript code.  Since Lagrange (fortunately) does not support JavaScript, this should be WONTFIX.

**Comment by skyjake** [comment] 2021-02-02 10:34
@johnwcowan  Ah but the problem is that Lagrange isn't sending the HTTP(S) URL to the server, it is passing the URL to a web browser. The fragment must be included so that any client-side behavior like jumping to a heading will work.

**Closed as completed** 2021-02-03 18:52 UTC
Labels: bug
