### ISSUE TITLE
Segfault on downloading ZIP file from agate server

### ISSUE THREAD

**Issue by mentalswarf** [skyjake/lagrange#498] opened 2022-05-13 00:08 UTC
Hi, I tried to reach you over the Fediverse about this, but it occurred to me that wasn't guaranteed.

The current Lagrange on iOS and MacOS are both segfaulting when attempting to download any ZIP file from my gemini server. The server is agate 3.2.3. It does not appear to affect ZIP files on other servers, because the MP3 packs by Konpeito Media (gemini://konpeito.media/) download without problems. Not sure what they are using to serve their capsule.

The files download normally in bombadillo and telescope, so whatever is wrong is only affecting Lagrange. You can attempt to download any of the files linked in my index of public gemstone designs to reproduce the problem.

gemini://mentalswarf.com/projects/open-gems/Broadfoot,%20John/

The same files are accessible over HTTP using my kineto proxy. https://mentalswarf.com/projects/open-gems/Broadfoot,%20John/

Relevant hardware/software:
Lagrange 1.13.4 on 2016 MacBook Pro running OS 11.6.5 (Big Sur)
Lagrange 1.13 (2) via Testflight on iPhone XR running iOS 14.5.1

**Comment by skyjake** [comment] 2022-05-13 04:00
I tested the ZIPs and there is a bug here with parsing the file path. Seems to be pretty recently introduced. Will fix.

I also tried the .asc files and your server is sending the MIME type "application/pgp-signature" for these. Seems unintentional?

**Comment by mentalswarf** [comment] 2022-05-13 07:48
Yeah, "application/pgp-signature" is definitely unintentional.

A quick look at the source seems to show it attempting to guess MIME types. I have no idea where it is getting this: /etc/mime.types contains the line:

> text/plain asc txt text pot brf srt

So I guess agate doesn't really care what system MIME says. :( Will need to create a .meta file to force text/plain for *.asc.

**Comment by skyjake** [comment] 2022-05-13 09:01
I don't which version of Agate introduced this feature, but you can put a `.meta` file in the directory to control the MIME types: https://github.com/mbrubeck/agate#meta-presets

**Comment by mentalswarf** [comment] 2022-05-13 16:32
I'm going to go ahead and do that. If I change the capsule, do you already have all the info you need to fix the segfault?

Edit: New problem. I've added a meta to all folders to specify "application/octet-stream" as the MIME for ASC files. Now Lagrange is trying to display them as text. When you save them, Lagrange is nuking the ".asc" extension so they aren't associated with anything.

Is there a MIME type that will just force a download?

**Comment by skyjake** [comment] 2022-05-13 18:07
You mean it removes the .asc extension? That surely is a bug...

**Comment by skyjake** [comment] 2022-05-13 18:09
To force a download, one can right-click on a link and use "Download Linked File".

The intended behavior is that once a file is downloaded, it can still be saved as-is, though.

**Comment by mentalswarf** [comment] 2022-05-13 20:28
gemini://mentalswarf.com/projects/open-gems/Affholter,%20Audrey/PC%2013.035%20Electron%20%233A.asc

If you save this file Lagrange is stripping the extension.

**Comment by skyjake** [comment] 2022-05-14 04:44
> If you save this file Lagrange is stripping the extension.

The %23 in that URL was confused with the `#` URL character, causing the file name to be incorrectly formed. This is now fixed.

**Comment by skyjake** [comment] 2022-05-14 14:01
The fixes will be included in v1.13.5.

**Closed as completed by skyjake** 2022-05-14 14:01 UTC
Labels: bug
